#!/usr/bin/env bash
#script that prints 100 numbers and FizzBuzz Buzz Fizz
COUNT=1
while [ $COUNT -lt 101 ]
do
    if [ $((COUNT%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((COUNT%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((COUNT%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$COUNT"
    fi
    (( COUNT++ )) || true
done