#!/usr/bin/env bash
#script that prints best school 10 times
COUNT=1
while [ "$COUNT" -le 20 ];
    do
    echo "$COUNT"
    case "$COUNT" in
4)
    echo "bad luck from China"
    ;;
9)
    echo "bad luck from Japan"
    ;;
17)
    echo "bad luck from Italy"
    ;;
    esac
    (( COUNT++ )) || true
done