#!/usr/bin/env bash
# displays numbers from 1 to 20.
HOURS=0
while [ $HOURS -lt 13 ]
do
    echo "Hour: $HOURS"
    MINUTES=1
    while [ $MINUTES -lt 60 ]
    do
        echo $MINUTES
	
    (( MINUTES++ )) || true
    done
    
    (( HOURS++ )) || true
done