#!/usr/bin/env bash
# Kills the process of 4-to_infinity_and_beyond.
echo "$$" > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while true; do
      echo "To infinity and beyond"
      sleep 2
done