#!/usr/bin/env bash
#Prints infinity and beyond infinite times,when receives the SIGTERM signal print "I am invincible"
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done